name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '10 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "pt_BR"
          SHOW_COMMIT: "True"
          SHOW_PROJECTS: "True"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE: "false"
          SHOW_OS: "false"
          SHOW_EDITORS: "false"
          SHOW_LANGUAGE_PER_REPO: "false"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
        
