name: Wakatime

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme 
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_SHORT_INFO: "True"
          SYMBOL_VERSION: 2
